### ISSUE TITLE
French is not yet supported may I help?

### ISSUE THREAD

**Issue by khzd** [petergridge/Irrigation-V5#28]

**Comment by petergridge** [comment]
Hi, that would be great. 

All you need to do is take a copy of the strings.json and modify the text part of each pair of items and save it as fr.json in the translations directory of your instance

![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/7f68a8ce-a701-4e4d-a5ad-b2fbb70e2e39)

Are you OK to fork the repository and then raise a Pull request to merge back once you have created the fr.json and saved into the translations directory of the archive?

I would recommend creating a development environment on your PC it makes testing so much faster if you have the time/inclination to set it up. https://developers.home-assistant.io/docs/development_environment/

To test the file (if you do not have a development environment) save it into the translations directory of your installation of the component and restart HA. You will need to refresh the browser to pick up the new version after each change.

I am really surprised that since this has made it onto HACS it has reached 1000+ users.

We are heading to France in October for a 3 week holiday, Lyon, Dordogne, Bordeaux, Loire Valley and Paris. We are excited for the trip, it is a long way from Australia so always a privilege to be able to travel in Europe.
 
Thanks for volunteering to add French.

Cheers
Pete
