### ISSUE TITLE
Watering Adjuster feature not working

### ISSUE THREAD

**Issue by Orishas** [petergridge/Irrigation-V5#32]
Hi, i created a number helper for watering adjustment 0 -2 increase 0,1.
My Problem is, it isn't working. My guess is the increase is seperated with a comma not an dot.
But this setting comes through my home assistant language settings.

**Comment by petergridge** [comment]
Hi @Orishas 

The language setting should not impact, HA will still provide a numeric value.

* Do you have any errors in the log?
* Can you send me a screenshot of your zone configuration and number helper configuration

**Comment by Ficus3** [comment]
Hello,
No problem for me, I installed your repository since 4days, and it's seem work fine.
It's just an idea about water adjustement value. First, I define factor 0 to 100, with % unit. 
Of course the time "on" was very long.

After, I have read the documentation, an I applied the correction to limit the factor between 0 to 1.
Maybe it's easier to talk about % (0 to 100). 

For my situation, I try to modify your "irrigationzone.py" like this :
water_adjust_value = float(self.hass.states.get(self._water_adjust).state)*0.01

I'm not expert, but it seem work :-)
Thanks for all !

**Comment by petergridge** [comment]
I prefer to work using a factor not %, but each to our own. The only downside of modifying my the code is you will need to do this with every release. 

Anyway letting you know I have released a new version, currently beta2 on the main repository so if you installed the ALPHA version I would recommend you move to the main release
