### ISSUE TITLE
Problem with irrigation Frequency / Openweather Map / Unit Type

### ISSUE THREAD

**Issue by GobiRan** [petergridge/Irrigation-V5#34]
Dear petergridge,

thank you very much for your effort, your irrigation automation seems to satisfy my needs to a large extent. 
two small problems / questions have and I and maybe you have an answer to them: 

1. if I create a sensor as specified in the documentation via the Openweathermap History as a template and want to return numbers for the irrigation frequency, then I always get a value e.g. 2.0 instead of 2 or 4.0 instead of 4. But your Irrigation can not handle this, so that the irrigation remains inactive. 

Example: 
{% set avgtemp = (forecast1max + forecast2max + forecast3max)/3 -%}
{% if avgtemp < 10 -%}
Off
{% elif avgtemp < 20 -%}
4
{% else -%}
2
{% endif -%}

3. if I use the above example with strings: 

{% set avgtemp = (forecast1max + forecast2max + forecast3max)/3 -%}
{% if avgtemp < 10 -%}
Off
{% elif avgtemp < 20 -%}
Mon, Fri
{% else -%}
Mon, Thu, Sat
{% endif -%}

Then there is always the newline character at the end (\n). It only works if I make the query without spaces: 

{% set avgtemp = (forecast1max + forecast2max + forecast3max)/3 -%}
{% if avgtemp < 10 -%}
Off
{% elif avgtemp < 20 -%}
Mon, Fri{% else -%}
Mon, Thu, Sat{% endif -%}

Maybe you have an idea.

Many greetings

Robert

**Comment by petergridge** [comment]
Hi, 

I am working on an update now, a alpha version is being tested, I have fixed the new line issue.

I will work on the 2/2.0 issue as well.

**Comment by petergridge** [comment]
Hi,

I have a new alpha version, this will need to be deployed using the HACS custom repositories.
image

There are two components to install:

The component: [GitHub - petergridge/irrigation_alpha 3](https://github.com/petergridge/irrigation_alpha)
The card: [GitHub - petergridge/irrigation_card_alpha 2](https://github.com/petergridge/irrigation_card_alpha)
Copy these links when using the custom repository configuration.


Support the RainBird run service
Implement changes to support more control in the custom card &
Changes to allow less strict coding of openWeatherHistory templates
The new custom card is required with this version the current version is not compatible.
Fix passing frequency from a sensor, handle format like '2.0'

Add visual editor for the custom card
Support showing config for one section at a time instead of all zones.
Beware this is a Alpha release so you will almost certainly find a bug or two, let me know we will get this up and running.

**Comment by petergridge** [comment]
If you have issues installing this please uninstall the component and custom  card. I think I have the update process working now though.

**Comment by GobiRan** [comment]
Hello Peter, you put in a lot of effort and do an amazing amount of work, thank you very much! Can I donate something to you? I have the following question about your versioning: It seems like when there's an update, I have to uninstall the current irrigation component and card, and then install the new version. This way, I would keep losing all the settings, zones, and programs each time. Setting these up takes quite a bit of time, and it would be nice if there were a way to carry them over or directly load an update. Or have I misunderstood something? How do you personally handle this? You probably wouldn't want to go through the effort of setting everything up anew each time, right?

**Comment by petergridge** [comment]
Normally that is not the case, the version you are installing now is using a different repository as it alpha version, in the next week or so I will push this to the mainstream repository. I have to do this as the alpha can occasionally be unstable and I need to publish it in the same way so I can test the full lifecycle and I don't want people installing the new version by accident.

This release is also implementing a new model for the custom card. Over all I have more testing to do before I put it out to make sure the configuration is not impacted.

Thanks for the offer of a donation, I have been using HA for some time and this is my donation to the community. Maybe if I am ever in your neck of the woods you can buy me a beer or wine.

If you don't mind me asking where are you? I am in Australia but most users are in the Northern Hemisphere.

**Comment by GobiRan** [comment]
I understand. I'd be content with waiting for the stable version. Currently, I'm utilizing the frequency over the weekdays, so it's functioning for now. Once the update is available, I'll switch to the numerical frequency in days since it allows for more precise irrigation intervals.

Indeed, I also hail from the northern region. I reside in Germany (near Berlin). If you happen to be in the vicinity, I'd be delighted to invite you for a beer in my garden : )

**Comment by petergridge** [comment]
I'm heading for France in a 6 weeks, I was in Germany last year for 3 days in Boppard, we stayed in Bad Salzig, and a brief stop in Frankfurt. I also enjoyed the area around the Austrian border had a beautiful day around Konigsee. This year rather than trying to see a lot of countries we are spending our time driving around France with only two cities Lyon and Paris on our itinerary, we enjoy staying in smaller towns and scenic locations.

**Comment by GobiRan** [comment]
Dear Peter,

Thank you very much for your effort. Within HACS, updates are likely only displayed if they are not marked as pre-release, correct? When do you plan to merge the version into the main release so that an update can be done through HACS?

Warm regards,
Robert

**Comment by petergridge** [comment]
Hi, I have moved this to the main version now. There have been 17 downloads and only one issue (fixed) so it is probably safe to deploy more broadly now.

If you have installed the alpha version in the links above you will need to uninstall that and install the main HACS version. 

You can choose to see the Beta/Pre Release versions by selecting the option on the download/redownload page in HACS
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/38e8f97d-3fe0-49e2-8a54-a6058dac5eba)

**Comment by GobiRan** [comment]
Dear Peter,

That was quick, thank you very much. I'm downloading it right away. Also, thanks for the information about the beta version, I wasn't aware of that; otherwise, I would have tested it already.

Best regards,
Robert

**Comment by GobiRan** [comment]
Dear Peter,

Wow, great job, it works perfectly! Thank you so much; your irrigation logic meets my needs 100%. Sending warm greetings to you in Australia.

Robert
