### ISSUE TITLE
ECO Mode with multiple zones question

### ISSUE THREAD

**Issue by mishoboss** [petergridge/Irrigation-V5#39]
I would like to have a program that runs at 8:00, 10:00, 12:00, 14:00, 16:00, 18:00, 20:00.
I have 4 zones inside, each zone should run for 5 minutes. Once one finishes, then the next one runs.

Is this config correct in my case? Is there a way I can see the config YAML? Any way I can test and/or simulate it?

<img width="505" alt="image" src="https://github.com/petergridge/Irrigation-V5/assets/1629929/effb7603-2888-4c3e-ae3f-f3bca90d25bd">

**Comment by petergridge** [comment]
Hi,

The design of this is based around a program having a start time and then the triggering a series of zones. The control currently does not support multiple start times.

To satisfy the requirement you describe you will need to replicate your program for each start time, 7 individual programs.

The eco mode is designed for shorter delays, in my case pot plants where waiting a minute or two before watering again allow the water to absorb more completely rather than running through the pot and onto the ground.

I will investigate the ability to provide multiple start times for a program as it is a meaningful use case.

**Comment by petergridge** [comment]
Hi,

I have released V5.4.0 that supports providing multiple start times to a program. This should help you implement your requirement much more effectively.

Please let me know if this works and close this issue.

Cheers
