### ISSUE TITLE
Irrigation_event (action: program_turned_on) is not call when no zone active or rain sensor is true 

### ISSUE THREAD

**Issue by Loic691** [petergridge/Irrigation-V5#53]
event program_turned_on is not fired when in the program no zones are ok to rain (disabled or rain).
In my example I have 5 zones (4 disabled and 1 enable but this last one have the rain sensor to true)

```
event_type: irrigation_event
data:
  action: program_turned_on
```

I think rain sensor must be called each time program is call even if zones turn off or rain sensor set.
The question should be asked for zone turned_on event... ???

In my case I have to compute the rain sensor state before each irrigation programs launch..
Compute past rain and daily rain forecast.

**Comment by petergridge** [comment]
Hi,

I rely on the sensor updating independently of the irrigation system. I am aware of some users using the event to start pumps and other devices so I need to be cautious of changing this away from indicating when a program is actually going to start.

I am not sure what process/data you are using to calculate the state, maybe you can automate it to recalculate each hour. Happy to have assist if you need.

I am using the OpenWeatherMapHistory  integration that uses history and forecast weather to change the amount of water applied rather than a binary sensor, it can also provide a binary sensor if required. This uses Open Weather Map data to calculate a sensor and is available on HACS. While you need to sign up for the OWM API you can configure the API to not exceed the free calls.

**Comment by Loic691** [comment]
Hi @petergridge 
Thanks. Yes I made a rain binary template sensor which compute in real time if rainy few days ago or rainy on day forecast. I will improve to change the amount of water to apply   with as your suggestion.

For now, can you describe the behaviour if rain sensor is ON at the time of launching irrigation program and my run every ifs define to 3 days for example. What'is the next  date/time cycle of irrigation ? Tomorrow ?

**Comment by petergridge** [comment]
If the rain sensor is on it will still try to water again at the same time the next day

**Comment by Loic691** [comment]
> If the rain sensor is on it will still try to water again at the same time the next day

Great 
Checked => It's working !

**Comment by Loic691** [comment]
For information, I'm usingthe rain sensor to add the availability or not, in addition to rain, to not launching zone irrigation if I have clothes on clothes rack  ;-)
It will be great because, my clothes input binary is reset 24h after swithching be on...
My next step is to check the presence of clothes with detection object in frigate with camera ;-) instead of pushing the switch manually on the dashboard tablet !!!

**Comment by Loic691** [comment]
> > If the rain sensor is on it will still try to water again at the same time the next day
> 
> Great Checked => It's working !
> 
> Maybe to add in the docs ;-)

Same behaviour if rain factor is null (0) ?
When is the next cycle start date ? Tomorrow or next cycle ?

**Comment by petergridge** [comment]
Yes same behaviour
