### ISSUE TITLE
Remaning time always stays the same

### ISSUE THREAD

**Issue by xtypebox** [petergridge/Irrigation-V5#64]
Hello,

In my configuration the Remaning time always stays the same, so the switch doesn't turn off after the time I set.

Thanks

**Comment by petergridge** [comment]
Hi,

Can you check you log for errors, and send me  screen shots of you config. 

Some people have found a restart of HA can help.

**Comment by magno-santos** [comment]
I also have the same issue, but only occurs with 1 zone. The last one.
Basically when this zone quicks in, the program finishes, not counting down that zone and thus never ending. This only occurred after one of the last updates, before it was perfect.

Already rebooted HA.

**Comment by magno-santos** [comment]
It seems that deleting the zone and adding it again solved it.

**Comment by petergridge** [comment]
That is odd,  indicates the config was corrupted during an update.

**Comment by magno-santos** [comment]
Now it skipped Zone 2 (started and exited zone immediately). I have in total 3 zones. 

Guess will delete and add again all zones

**Comment by petergridge** [comment]
I have been looking into this issue. The behaviour you describe happens when the zone switch is not available or has significant latency/does not update state fast enough. 

I have tweaked the code to handle the unavailable switch scenario better, I will include this in the next release.

There is not much I can do where the switch does not change state within 10 seconds of being started in this case the zone may start and not be turned off.

**Comment by petergridge** [comment]
V5.4.15 adds better treatment for 0 time, highlighting that the zone is currently disabled.
