### ISSUE TITLE
feature request : support valve entity

### ISSUE THREAD

**Issue by Yogui79** [petergridge/Irrigation-V5#68]
Hello,
thank you for the job you do for this integration/
I will be nice it also support the Entity valve added in HA 2024.1 (https://www.home-assistant.io/integrations/valve/)  additionaly to the entity switch for the solenoid

regards
   yogui

**Comment by petergridge** [comment]
Hi, 
To clarify the requirement, you want to be able to define a valve instead of a switch when configuring the component?

I do not have any devices that are presented as a valve, but assuming the valve.open, valve.close services are the equivalent of switch.on and switch.off services then it should not be a huge problem, it would be even better if they responded to the switch commands  the change would then be very simple.

I will need to understand the set to position requirement if that is needed. What device do you use that is a valve?

**Comment by Yogui79** [comment]
Hello
thank you for your anwer
yes It will be fine  to also be able to define a valve instead of a switch.

I have a self made (ESP32 + relay) MQTT node . onestly it's not 100% necessary to have this feature. it's more a nice to have feature 
regards
   yogui

**Comment by martindybal** [comment]
Hello, any progress here? I have valve entities from the TapHome component. I can map them to switches, but I agree with @Yogui79 that it would be nice to have this feature. In fact, the valve should be the default entity for solenoids. :-)

**Comment by petergridge** [comment]
Hi Martindybal, No progress as yet, I have not had an opportunity to get or build a device that emulates a valve for testing, it still remains on my todo list.

**Comment by martindybal** [comment]
You can simple use a virtual device. Or if you need I can prepare it for you.

**Comment by petergridge** [comment]
Hi, V5.4.17 currently Beta has support for valve, I would appreciate if you could test this and let me know if you experience any issues, I have test only with a valve that is the result of changing the device type of a switch

**Comment by lorenzing** [comment]
> y Beta has support for valve, I would appreciate if you could test this and let me know if you experience any issues, I have test only with a valve that is the result of changing the device type of a switch

I'm testing it with good results. Good job!

**Comment by petergridge** [comment]
Great thanks

**Comment by martindybal** [comment]
Thank you. Looks pretty good!
