### ISSUE TITLE
[Discussion] - What is your prefered irrigation parameters for lawn

### ISSUE THREAD

**Issue by Loic691** [petergridge/Irrigation-V5#85]
Hey
I'm asking few question about irrigation for lawn :
- Time cycle
- Irrigation in several times into one cycle
- Duration
- Frequency
- Forecast
- Pas weather (rain and/or temperature)
- ....

What are you using for best lawn ?

For my self, I'm using rain past for 2 days and 2 days rain forecast
I'm changing frequency with automation depending of max temperature in last 2 days

I'm stoping irigation (raining sensor of irrigation V5 integration) when amout of rain in last 2 days is triger

For the duration, I know surface of each zone and the water bitrate, so I can approx compute mm of water for each zone and I have a input number helper to set mm of water I want . So with this I can  compute ajustement and rain factor.

What are you thinking of this ?
For myself I'm not clear about amount of water I have to set for lawn depending on the weather
I know and read it's preferable to launch irrigation less often and longer to give deep irrigation and less surface one...

**Comment by petergridge** [comment]
This would be a great question to put on the forum, you will likely get more responses there.

For an Australian lawn we tend to water longer and less often. This encourages the roots to seek water deeper and as a result are stronger and more resilient to the hot weather. In Western Australia you are only allowed to water twice a week and then only in the early morning or evening. On the east coast there is more rainfall but we are still encouraged to be waterwise. 

I use the forecast and history data to reduce the watering rather than fully stop the watering unless of course there has been enough rain. At the end of the day the strategy is to save water.

I have not tried to be to scientific, I have changed the watering model until I felt it worked, reduce the watering time, tried eco mode where there was run off... the options are endless.
